### ISSUE TITLE
[Forge] compatibility with java 17?

### ISSUE THREAD

**Issue by kuba26038** [Estecka/mc-Simple-Water-Gravity#2]
as it turns out, this mod doesn't exactly work with the infamous mod known as sintyra connector. i've talked to the devs of that mod about this, and it might be only because the mod is made to not work with java 17. i assume it's also a problem for fabric users who use that version of java, so i'd like to suggest having backwards compatibility with java 17, at least on the 1.20.1 version

**Comment by Estecka** [comment]
Just to get this out of the way, have you tried running the game with Java 21 ? From experience, older version of the game and older mods will work on Java 21. Unless Synitra does some cursed thing with the Java VM itself, I don't see a reason it wouldn't work.

Trying to override the dependency in the mod itself probably won't work.

**Comment by Estecka** [comment]
I assume this is the regular Forge loader, right ?

After a quick test, it can run on the latest Forge using Java 21, but still requires the mod to lie and declares `JAVA_17` as its mixin compatibility... which I really didn't expect would work.
That means someone else, either Sinytra or Forge itself, is actively shutting down attempts at using java 21 mixins. Since those seem to work, they should probably remove that barrier on their end.

**Comment by kuba26038** [comment]
I've just removed the java 21 recquirement from the dependencies of your mod and, yeah, works perfectly. I assume you can do that as well, but it doesn't matter to me specifically anymore, so do as you wish, thank you for your time

**Comment by Estecka** [comment]
I'm not sure that intentionally declaring the *wrong* version of java is the best course of action. This particular jar I can entirely recompile with Java 17, but I'm concerned about other mod jars that are cross-compatible with MC 1.20.5, and may require to be compiled with Java 21.

**Comment by Estecka** [comment]
I've added a Java17 jar as an additional file under the existing [1.0.2+1.20.1](https://modrinth.com/mod/simple-water-gravity/version/1.0.2+1.20.1) release.
